[build]
  command = "npm run build && cp -r backend/ netlify/functions/"
  publish = "src/dist"
  functions = "netlify/functions"



[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[dev]
  command = "npm run dev"
  targetPort = 3000