[build]
  command = "cd backend && npm install && cd .. && npm run build"
  publish = "src/dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[dev]
  command = "npm run dev"
  targetPort = 3000
