[build]
  command = "npm run build && (cd backend && npm install) && cp -r backend/ netlify/functions/"
  publish = "src/dist"
  functions = "netlify/functions"

# Map /api/* to serverless functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

# SPA fallback LAST
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run dev"
  targetPort = 3000