[build]
  command = "npm run build && cp -r backend/ netlify/functions/"
  publish = "src/dist"
  functions = "netlify/functions"

# 1) Let functions pass through untouched
[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200

# 2) (Optional) Map /api/* to your functions for cleaner frontend URLs
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

# 3) SPA fallback LAST — don't put this above the others
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run dev"
  targetPort = 3000