[build]
  command = "npm run build && cp -r backend/ src/dist/"
  publish = "src/dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[dev]
  command = "npm run dev"
  targetPort = 3000
